[workspace]
members = [
    "cli",
    "contracts",
    "methods",
]

[workspace.dependencies]
risc0-zkp = { version = "0.13" }
risc0-zkvm = { version = "0.13" }
risc0-build = { version = "0.13" }
hello-bonsai-methods = { path = "methods" }
hello-bonsai-contracts = { path = "contracts" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
