[package]
name = "hello-bonsai-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
risc0-zkp = { workspace = true }
risc0-zkvm = { workspace = true }
hello-bonsai-methods = { workspace = true }
